# frontend/Dockerfile

# Используем официальный образ Node для сборки
FROM node:20 AS build

WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY package*.json ./
RUN npm install

# Копируем весь проект и собираем
COPY . .
RUN npm run build

# Этап сервера — минимальный nginx
FROM nginx:alpine

# Копируем собранные файлы во внутренний каталог nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем кастомный конфиг, если нужно
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
