FROM ubuntu:22.04

WORKDIR /app
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglu1-mesa \
    libx11-dev \
    libxext-dev \
    libxtst-dev && \
    rm -rf /var/lib/apt/lists/*
RUN apt update && apt upgrade -y 
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update
RUN apt install -y python3.10 python3.10-venv python3.10-dev
RUN apt install -y python3-pip
COPY requirements.txt .
RUN pip install 'numpy<1.24'
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
#RUN groupadd -r docker-gpus && adduser whoami docker-gpus
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


# Базовый образ с CUDA и Python 3.10
# FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

# # Установка системных зависимостей
# RUN apt-get update && apt-get install -y \
#     python3.10 python3.10-dev python3-pip python3-setuptools \
#     gdal-bin libgdal-dev \
#     gcc g++ \
#     libgl1-mesa-glx libglib2.0-0 \
#     curl wget unzip \
#     && rm -rf /var/lib/apt/lists/*

# # Обновляем pip и устанавливаем Python зависимости
# RUN python3.10 -m pip install --upgrade pip

# # Устанавливаем зависимости
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
# RUN pip install -r requirements.txt

# # Копируем весь проект
# COPY . .

# # Открываем порт
# EXPOSE 8000

# # Запускаем FastAPI
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
